# Generated by Django 4.0.4 on 2022-05-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='Hello This is Default Description Of your Profile, Please Change it.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='static/images/default_profile.png', null=True, upload_to='static/images'),
        ),
    ]
