# Generated by Django 4.0.4 on 2022-05-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallRequest',
        ),
    ]
