# Generated by Django 4.0.4 on 2022-08-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reports',
            new_name='DashReports',
        ),
    ]
