# Generated by Django 4.0.4 on 2022-06-01 10:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0018_rename_instalment_buyproperty_monthly_instalment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.CharField(max_length=70, unique=True)),
                ('content', models.TextField()),
                ('property_img1', models.ImageField(blank=True, null=True, upload_to='static/images/bidding')),
                ('property_img2', models.ImageField(blank=True, null=True, upload_to='static/images/bidding')),
                ('property_img3', models.ImageField(blank=True, null=True, upload_to='static/images/bidding')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='static/images/bidding')),
                ('bidding_start_price', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=240)),
                ('city', models.CharField(default='', max_length=240)),
                ('room', models.IntegerField(default=0)),
                ('bathroom', models.IntegerField(default=0)),
                ('kitchen', models.IntegerField(default=0)),
                ('floor', models.IntegerField(default=0)),
                ('marla', models.FloatField(default=0.0, max_length=4)),
                ('is_live', models.BooleanField(default=False)),
                ('on_banner', models.BooleanField(default=False)),
                ('end_bidding', models.DateTimeField()),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='properties.category')),
            ],
        ),
        migrations.CreateModel(
            name='BiddingParticipator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_price', models.IntegerField()),
                ('bidding_time', models.DateTimeField(default=datetime.datetime(2022, 6, 1, 3, 8, 54, 657067))),
                ('item', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bidding.lot')),
                ('paricipator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
