# Generated by Django 4.0.4 on 2022-06-14 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_remove_lot_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingparticipator',
            name='bidding_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 1, 27, 45, 854322)),
        ),
    ]
