# Generated by Django 4.0.4 on 2022-05-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyproperty',
            old_name='b_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='buyproperty',
            old_name='b_bathroom',
            new_name='bathroom',
        ),
        migrations.RenameField(
            model_name='buyproperty',
            old_name='b_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='buyproperty',
            old_name='b_kitchen',
            new_name='kitchen',
        ),
        migrations.RenameField(
            model_name='buyproperty',
            old_name='b_property_img1',
            new_name='property_img1',
        ),
        migrations.RenameField(
            model_name='buyproperty',
            old_name='b_property_img2',
            new_name='property_img2',
        ),
        migrations.RenameField(
            model_name='buyproperty',
            old_name='b_property_img3',
            new_name='property_img3',
        ),
        migrations.RenameField(
            model_name='buyproperty',
            old_name='b_property_price',
            new_name='property_price',
        ),
        migrations.RenameField(
            model_name='buyproperty',
            old_name='b_room',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='buyproperty',
            old_name='b_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='buyproperty',
            old_name='b_thumbnail',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='buyproperty',
            old_name='b_title',
            new_name='title',
        ),
    ]
