# Generated by Django 4.0.4 on 2022-05-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_buyproperty_floor_buyproperty_marla'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproperty',
            name='address',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
    ]
