# Generated by Django 4.0.4 on 2022-05-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_buyproperty_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproperty',
            name='bathroom',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='buyproperty',
            name='floor',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='buyproperty',
            name='kitchen',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='buyproperty',
            name='room',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
