# Generated by Django 4.0.4 on 2022-05-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_buyproperty_bathroom_alter_buyproperty_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproperty',
            name='bathroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buyproperty',
            name='floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buyproperty',
            name='kitchen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buyproperty',
            name='room',
            field=models.IntegerField(default=0),
        ),
    ]
