# Generated by Django 4.0.4 on 2022-05-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_buyproperty_bathroom_alter_buyproperty_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproperty',
            name='property_price',
            field=models.CharField(max_length=30),
        ),
    ]
