# Generated by Django 4.0.4 on 2022-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_buyproperty_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproperty',
            name='slug',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
