# Generated by Django 4.0.4 on 2022-05-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproperty',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='properties.category'),
        ),
    ]
