# Generated by Django 4.0.4 on 2022-05-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_buyproperty_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproperty',
            name='advance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buyproperty',
            name='city',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='buyproperty',
            name='monthly_instalment',
            field=models.IntegerField(default=0),
        ),
    ]
