# Generated by Django 4.0.4 on 2022-05-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_buyproperty_advance_buyproperty_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproperty',
            name='lease_complete_in_years',
            field=models.IntegerField(default=0),
        ),
    ]
