# Generated by Django 4.0.4 on 2022-05-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_alter_buyproperty_property_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyproperty',
            old_name='monthly_instalment',
            new_name='lease_complete_price',
        ),
    ]
