# Generated by Django 4.0.4 on 2022-05-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_rename_lease_complete_price_buyproperty_instalment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyproperty',
            old_name='instalment',
            new_name='monthly_instalment',
        ),
    ]
