# Generated by Django 4.0.4 on 2022-05-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticposts',
            name='page_name',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staticposts',
            name='content',
            field=models.TextField(default='Un-Named'),
        ),
    ]
