# Generated by Django 4.0.4 on 2022-05-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_staticposts_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=160)),
                ('phone', models.IntegerField(default=123456789, max_length=14)),
                ('facebook', models.CharField(default='', max_length=160)),
                ('instagram', models.CharField(default='', max_length=160)),
                ('twitter', models.CharField(default='', max_length=160)),
                ('youtube', models.CharField(default='', max_length=160)),
                ('address', models.CharField(default='', max_length=260)),
                ('made_by', models.CharField(default='', max_length=160)),
                ('copyright', models.CharField(default='', max_length=160)),
            ],
        ),
    ]
