# Generated by Django 4.0.4 on 2022-05-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_footerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerdata',
            name='phone',
            field=models.IntegerField(default=123456789),
        ),
    ]
