# Generated by Django 4.0.4 on 2022-05-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_footerdata_address_alter_footerdata_copyright_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerdata',
            name='address',
            field=models.CharField(default='', max_length=260),
        ),
        migrations.AlterField(
            model_name='footerdata',
            name='copyright',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='footerdata',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='footerdata',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='footerdata',
            name='made_by',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='footerdata',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='footerdata',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=160, null=True),
        ),
    ]
