# Generated by Django 4.0.4 on 2022-05-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_footerdata_address_alter_footerdata_copyright_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticposts',
            name='page_name',
            field=models.CharField(max_length=70),
        ),
    ]
